// Code generated by Node.js script
package app.himawari.dto.json

import com.fasterxml.jackson.databind.ObjectMapper
import org.junit.Test

/**
 * Api0003Requestのテストクラスです
 */
internal class Api0003RequestTest {
    @Test
    fun fullProperty() {
        val api0003Request = Api0003Request().apply {
            id = ""
        }
        println(ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(api0003Request))
    }
}