swagger: '2.0'

info:
  version: "0.0.1"
  title: himawari

paths:
  /login:
    post:
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
      responses:
        200:
          description: Successful response
  /logout:
    post:
      consumes:
        - application/x-www-form-urlencoded
      responses:
        200:
          description: Successful response
