swagger: '2.0'

info:
  version: "0.0.1"
  title: himawariAPI
basePath: /api/v1
produces:
  - application/json

paths:
  /users/{userId}/timecards/{yearMonth}:
    get:
      description: |
        月の開始、終了時間のリストを返します。
      parameters:
        - name: userId
          in: path
          description: ユーザーID
          required: true
          type: string
        - name: yearMonth
          in: path
          description: 年月(yyyyMM)
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            title: Timecard
            type: object
            properties:
              yearMonth:
                type: string
              days:
                type: array
                items:
                  type: object
                  properties:
                    bizDate:
                      type: string
                    startDate:
                      type: string
                    finishDate:
                      type: string
                    remarks:
                      type: string
