swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: himawariAPI
basePath: /v1
produces:
  - application/json

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /users/{user_id}/timecards/{year_month}:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Person` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: user_id
          in: path
          description: ユーザーID
          required: true
          type: string
        -
          name: year_month
          in: path
          description: 年月
          required: true
          type: string
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: Timecard
            type: object
            properties:
              year_month:
                type: string
              days:
                type: array
                items:
                  type: object
                  properties:
                    biz_date:
                      type: string
                    start_date:
                      type: string
                    finish_date:
                      type: string
                    remarks:
                      type: string