swagger: '2.0'

info:
  version: "0.0.1"
  title: himawariAPI
basePath: /v1
produces:
  - application/json

paths:
  /users/{user_id}/timecards/{year_month}:
    get:
      description: |
        月の開始、終了時間のリストを返します。
      parameters:
        - name: user_id
          in: path
          description: ユーザーID
          required: true
          type: string
        - name: year_month
          in: path
          description: 年月(yyyyMM)
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            title: Timecard
            type: object
            properties:
              year_month:
                type: string
              days:
                type: array
                items:
                  type: object
                  properties:
                    biz_date:
                      type: string
                    start_date:
                      type: string
                    finish_date:
                      type: string
                    remarks:
                      type: string
