swagger: '2.0'

info:
  version: "0.0.1"
  title: himawariAPI
basePath: /api/v1
produces:
  - application/json

paths:
  /users/{userId}/timecards/{yearMonth}:
    get:
      operationId: Api0001
      summary: API0001:開始/終了時間取得
      description: |
        対象月の日毎の開始/終了日時の一覧を返します。
      tags:
        - timecard
      parameters:
        - name: userId
          in: path
          description: ユーザーID
          required: true
          type: string
        - name: yearMonth
          in: path
          description: 年月(yyyyMM)
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            title: Timecard
            type: object
            properties:
              yearMonth:
                title: 年月
                type: string
              days:
                title: 日次データ
                type: array
                items:
                  type: object
                  properties:
                    bizDate:
                      title: 業務日
                      type: string
                      description: yyyy-MM-dd
                    startDatetime:
                      title: 開始日時
                      description: yyyy-MM-ddTHH:mm:dd:ss.SSSZ
                      type: string
                    endDatetime:
                      title: 終了日時
                      description: yyyy-MM-ddTHH:mm:dd:ss.SSSZ
                      type: string
                    vacationTypeCode:
                      $ref: '#/definitions/VacationType'
                    note:
                      title: 備考
                      type: string
  /user/days:
    post:
      summary: API0002:日次データ登録
      description: 日単位の開始、終了時間を登録します。
      tags:
        - timecard
      parameters:
        - name: StartEndDatetimes
          in: body
          schema:
            title: Request
            type: object
            properties:
              days:
                title: 日次情報リスト
                type: array
                items:
                  title: Day:日次情報
                  type: object
                  properties:
                    bizDate:
                      title: 業務日
                      description: yyyy-MM-dd
                      type: string
                    startDatetime:
                      title: 開始日時
                      description: yyyy-MM-ddTHH:mm:dd:ssZ
                      type: string
                    endDatetime:
                      title: 終了日時
                      description: yyyy-MM-ddTHH:mm:dd:ssZ
                      type: string
                    vacationType:
                      $ref: '#/definitions/VacationType'
                    note:
                      title: 備考
                      type: string
                  required:
                    - bizDate
      responses:
        200:
          description: 登録結果
          schema:
            title: Result
            type: object
            properties:
              resultType:
                title: 登録結果コード
                type: string
                enum:
                  - success
                  - failure
              message:
                title: 結果メッセージ
                type: string
            required:
              - resultType
################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  VacationType:
    title: 休暇タイプ
    type: string
    enum:
      - PAID_DAY_OFF
      - SP_DAY_OFF
      - AM_OFF
      - PM_OFF
      - TRANSFER_DAY_OFF
    description: |
      01,有給休暇
      02,特別休暇
      03,AM休
      04,PM休
      05,振替休暇
