version: '3'
services:
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
  logstash:
    restart: always
    image: docker.elastic.co/logstash/logstash:6.3.2
    container_name: logstash
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./data/logstash/lake:/usr/share/logstash/lake
    ports:
      - "4560:4560"
    links:
      - elasticsearch:elasticsearch
  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
