version: '3.2'
services:
  es1:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es1
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./data/es1:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
  es2:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es2
    environment:
      - TZ=Asia/Tokyo
      - "discovery.zen.ping.unicast.hosts=es1"
    volumes:
      - ./data/es2:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    links:
      - es1:es1
  logstash:
    restart: always
    image: docker.elastic.co/logstash/logstash:6.3.2
    container_name: logstash
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./data/logstash/lake:/usr/share/logstash/lake
    expose:
      - 5043
    ports:
      - "4560:4560"
    links:
      - es1:elasticsearch
  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "5601:5601"
    links:
      - es1:elasticsearch
  filebeat:
    restart: always
    image: docker.elastic.co/beats/filebeat:6.3.2
    container_name: filebeat
    volumes:
      - type: bind
        source: ./filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: bind
        source: ../../web/logs
        target: /app
    links:
      - es1:elasticsearch
      - logstash:logstash
