filebeat:
  inputs:
    - type: log
      enabled: true
      paths:
        - /app/*.log
output:
  logstash:
    hosts: ["logstash:5044"]
xpack:
  monitoring:
    enabled: true
    elasticsearch:
      hosts: ["http://elasticsearch:9200"]
