spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/himawari?useSSL=false
    username: himawari
    password: himawari
    driverClassName: com.mysql.cj.jdbc.Driver
app:
  log:
    filter:
      type: SIMPLE # NOTHING, SIMPLE, DEBUG
