spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/himawari?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: himawari
    password: himawari
    driverClassName: com.mysql.jdbc.Driver
app:
  datetime:
    timezone: Asia/Tokyo
    bizDate: ""
  log:
    filter:
      type: SIMPLE # NOTHING, SIMPLE, DEBUG
  security:
    enabled: true
  timecard:
    excel:
      templateFilePath: ./template/timecard.xlsx
      downloadFileName: timecard.xlsx
      outputSheetName: timecard
      beginRowNum: 1
      bizDateColumnIndex: 1
      startDatetimeColumnIndex: 2
      endDatetimeColumnIndex: 3
      vacationTypeColumnIndex: 4
      noteColumnIndex: 5
      autoSizeColumnIndexes: 1,2,3,4,5
