version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui:v3.0.5
    container_name: himawari_swagger_ui
    ports:
      - 8180:8080
    environment:
      API_URL: swagger.yml
    volumes:
      - ../../docs/swagger/swagger.yml:/app/swagger.yml
