version: '3'
services:
  nginx:
    image: nginx:1.15.2
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html:ro
      - ./data/log:/var/log/nginx
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 80:80
