---
properties:
- key: responseDelay
  title: レスポンス遅延(ms)
  type: number
  default: 0
  options:
    - value: 500
    - value: 1000
    - value: 5000
- key: responseHttpStatus
  title: HTTPステータス
  type: number
  default: 200
  options:
    - value: 404
    - value: 500
- key: mockSettingLog
  title: モック設定ログ
  type: boolean
  default: false
