// Code generated by Node.js script
package app.himawari.dto.json

import com.fasterxml.jackson.annotation.JsonInclude

/**
 * ユーザー一覧
 * @property users ユーザー情報リスト
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
data class Api1002Response(
        var users: List<Users> = listOf()) {
    /**
     * ユーザー情報リスト
     * @property userId ユーザーID
     * @property userName ユーザー名
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    data class Users(
            var userId: String = "",
            var userName: String = "")
}
