// Code generated by Node.js script
package app.himawari.dto.json

import com.fasterxml.jackson.databind.ObjectMapper
import org.junit.jupiter.api.Test

/**
 * Api0002Responseのテストクラスです
 */
internal class Api0002ResponseTest {
    @Test
    fun fullProperty() {
        val api0002Response = Api0002Response().apply {
            resultType = Api0002Response.ResultType.success
            message = ""
        }
        println(ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(api0002Response))
    }
}