// Code generated by Node.js script
package app.himawari.dto.json

import com.fasterxml.jackson.databind.ObjectMapper
import org.junit.Test

/**
 * Api0001Responseのテストクラスです
 */
internal class Api0001ResponseTest {
    @Test
    fun fullProperty() {
        val api0001Response = Api0001Response().apply {
            yearMonth = ""
            days = listOf(Api0001Response.Day().apply {
                bizDate = ""
                startDatetime = ""
                endDatetime = ""
                vacationType = VacationType.PAID_DAY_OFF
                note = ""
            })
        }
        println(ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(api0001Response))
    }
}