// Code generated by Node.js script
package app.himawari.dto.json

import com.fasterxml.jackson.databind.ObjectMapper
import org.junit.jupiter.api.Test

/**
 * Api1001Responseのテストクラスです
 */
internal class Api1001ResponseTest {
    @Test
    fun fullProperty() {
        val api1001Response = Api1001Response().apply {
            yearMonth = ""
            days = listOf(Api1001Response.Day().apply {
                bizDate = ""
                startDatetime = ""
                endDatetime = ""
                vacationTypeCode = Api1001Response.Day.VacationTypeCode.PAID_DAY_OFF
                note = ""
            })
        }
        println(ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(api1001Response))
    }
}