// Code generated by Node.js script
package app.himawari.dto.json

import com.fasterxml.jackson.databind.ObjectMapper
import org.junit.jupiter.api.Test

/**
 * StartEndDatetimesのテストクラスです
 */
internal class StartEndDatetimesTest {
    @Test
    fun fullProperty() {
        val startEndDatetimes = StartEndDatetimes().apply {
            days = listOf(StartEndDatetimes.Days().apply {
                bizDate = ""
                startDatetime = ""
                endDatetime = ""
                remarks = ""
            })
        }
        println(ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(startEndDatetimes))
    }
}