

/* Create Tables */

CREATE TABLE DAILY_START_END
(
	DAILY_START_END_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '日次勤務時間記録ID',
	TIMECARD_ID BIGINT NOT NULL COMMENT 'タイムカードID',
	BIZ_DATE DATE NOT NULL COMMENT '業務日',
	START_DATETIME DATETIME COMMENT '開始日時',
	END_DATETIME DATETIME COMMENT '終了日時',
	SCALE_FITTED_START_DATETIME DATETIME COMMENT '補正後の開始日時',
	SCALE_FITTED_END_DATETIME DATETIME COMMENT '補正後の終了日時',
	VACATION_TYPE_CODE VARCHAR(3) COMMENT '休暇タイプコード',
	NOTE TEXT COMMENT '備考入力テキスト',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザ',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザ',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号',
	PRIMARY KEY (DAILY_START_END_ID)
) COMMENT = '日次勤務時間記録';


CREATE TABLE MEMBER
(
	MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'メンバーID',
	MEMBER_NAME VARCHAR(100) NOT NULL COMMENT 'メンバー名称',
	MEMBER_ACCOUNT_ID VARCHAR(50) NOT NULL UNIQUE COMMENT 'メンバーアカウント',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザ',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザ',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = 'メンバー';


CREATE TABLE TIMECARD
(
	TIMECARD_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'TIMECARD_ID',
	MEMBER_ID BIGINT NOT NULL COMMENT 'メンバーID',
	TIMECARD_YEAR_MONTH VARCHAR(6) NOT NULL COMMENT '年月 : YYYYMM',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザ',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザ',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号',
	PRIMARY KEY (TIMECARD_ID),
	CONSTRAINT UQ_TIMECARD_MEMBER_MONTH UNIQUE (MEMBER_ID, TIMECARD_YEAR_MONTH)
) COMMENT = 'タイムカード';


CREATE TABLE VACATION_TYPE
(
	VACATION_TYPE_CODE VARCHAR(3) NOT NULL COMMENT '休暇タイプコード',
	VACATION_TYPE_NAME VARCHAR(200) NOT NULL COMMENT '休暇タイプ名称',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザ',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザ',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号',
	PRIMARY KEY (VACATION_TYPE_CODE)
) COMMENT = '休暇タイプ';



/* Create Foreign Keys */

ALTER TABLE TIMECARD
	ADD CONSTRAINT FK_TIMECARD_MEMBER FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DAILY_START_END
	ADD CONSTRAINT FK_DAILY_IN_OUT_TIMECARD FOREIGN KEY (TIMECARD_ID)
	REFERENCES TIMECARD (TIMECARD_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DAILY_START_END
	ADD CONSTRAINT FK_DAILY_IN_OUT_VACATION_TYPE FOREIGN KEY (VACATION_TYPE_CODE)
	REFERENCES VACATION_TYPE (VACATION_TYPE_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



